# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BDDDemo' do
  use_frameworks!

  target 'BDDDemoTests' do
    inherit! :search_paths
    pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
    pod 'Nimble', '~> 5.0'
  end

  # target 'CucumberishTests' do
  #   inherit! :search_paths
  #   pod 'Cucumberish', :git => 'https://github.com/Ahmed-Ali/Cucumberish.git', :branch => 'develop'
  #   pod 'KIF', '~> 3.5'
  #   pod 'Nimble', '~> 5.0'
  # end
end
